#!/bin/bash
git clone https://github.com/agkozak/zsh-z.git ~/.oh-my-zsh/custom/plugins/zsh-z
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
echo "----------------------------------------------------------------"
echo "change the line in the ~/.zshrc : plugins=(git)"
echo "by"
echo "plugins=(git zsh-syntax-highlighting zsh-autosuggestions zsh-z)"
echo "then run the folowing command : source ~/.zshrc"
echo "then restart your computer to ensure that all is setup correctly ^^"
echo "----------------------------------------------------------------"
