users:
  - name: test
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: sudo
    ssh_import_id:
      - gh:tooneur

package_update: true
package_upgrade: true
packages:
  - git
  - make
  - build-essential 

runcmd:
  - sleep 5 
  - sudo -u test -- git clone https://github.com/4a2s/setup_and_tips_unix-linux.git /home/test/setup_and_tips_unix-linux
  - sudo -u test -- bash -c "cd /home/test/setup_and_tips_unix-linux/set_your_ubuntu_faster && make code > /home/test/make_output.log"
  - sleep 5 
  - sudo -u test -- bash -c "cd /home/test/setup_and_tips_unix-linux/set_your_ubuntu_faster && ./a.out"